# Generated by Django 4.2.1 on 2024-06-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='related_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.task'),
        ),
    ]
